## Upstream dask image
ARG BASE=celsiustx/dask:dc6cc91ab379f4bb7c7ba2e01b75505dd47fb987
FROM $BASE

WORKDIR /opt/src

COPY . anndata
WORKDIR anndata
RUN git clean -fdx

## Install
RUN pip install -e .[test] \
 && pip install psycopg2 scanpy

RUN pytest -v

WORKDIR /
